"""add failed_logins and lockout_until

Revision ID: d55ee775fada
Revises: a5a366fd2407
Create Date: 2026-03-01 13:19:36.707333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55ee775fada'
down_revision = 'a5a366fd2407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('lockout_until')
        batch_op.drop_column('failed_logins')

    # ### end Alembic commands ###
